### ISSUE TITLE
Check for authentication from another controller

### ISSUE THREAD

**Issue by belst** [belst/rusty-diesel-rocket#4]
> Hey
> 
> I have a question about your project. I have been playing around with it and I want to know, how can I now check in another controller, if the user is authenticated. I wrote a post module and controller for writing posts. How can I now check if the user is logged in?
> For example in view_post, how can I see if the user is authenticated and display edit and delete buttons on the page?
> I have also put captcha on the login page (register is still TODO).
> If you want you can use the page controller (for testing) and the code for captcha in your project.
> After I fix captcha on register page, I can have a look at how to implement email confirmations.

**Comment by belst** [comment]
@Alko89 I moved your question to a new issue.

You can check if a user is authenticated in another controller the same way it is done in the user controller.

Simply `use` the `User` model and use it as a request guard.

**Comment by alko89** [comment]
Ok, I didn't know you can open a question issue :)
Can you give a small example? I'm fairly new to Rust.

**Comment by belst** [comment]
in your other controller:

```rust
use ::models::user::User;

#[post("/post")]
fn new_post(user: User) -> &'static str {
    // create post and stuff.
    "logged in and authenticated"
}
```

**Comment by alko89** [comment]
Ok, got it. But this is only ok for new and edit post. How about view_post? Do I have to create two functions to handle anonymous and logged in users?
I want to display edit buttons if the user is logged in.

**Comment by belst** [comment]
Yes, you have to create 2 functions. that's how rocket works.

you can create a 3rd function to handle the actual logic and just forward to that function in your 2 handlers

eg:

```rust
use ::models::user::User;

#[get("/post/<id>")]
pub fn post(user: User, id: usize) -> Template {
    show_post(id, true)
}

#[get("/post/<id>", rank = 2)]
pub fn post_guest( id: usize) -> Template {
    show_post(id, false)
}

fn show_post(id: usize, logged_in: bool) -> Template {
    // render template logic here
}

```

**Comment by belst** [comment]
@Alko89 did this resolve your issue?

**Comment by alko89** [comment]
I managed to make it work. But I still have to do some fixes, before I commit. I'll probably do it during the weekend, I don't have much time on weekdays. I'll tell you as soon as I commit.

**Comment by alko89** [comment]
There, its working now. Looks good, just a million fixes left. Thanks! 
Would you want to use posts in your project? It would be nice to have a "starter kit" for building web applications in Rust with basic authentication (and authorization) and some simple post editing.

**Comment by belst** [comment]
I am already thinking on how to best implement an access control system. Probably something like [RBAC](https://en.wikipedia.org/wiki/Role-based_access_control) with a level system for role hierarchy.

A sample Posts Model would be nice to have as a first use case for this.

I will open a new issue to discuss this further.
